spring.application.name=mall
spring.main.allow-circular-references=true

# OAuth 설정 파일을 선택적으로 로딩
spring.config.import=optional:classpath:application-oauth.properties

# 기본 실행 프로필
spring.profiles.default=local

# Mybatis 설정 : 컬럼명을 변수명으로 자동매핑 -> board_no => boardNo
mybatis.configuration.map-underscore-to-camel-case=true

# resultType 속성에서 domain 객체 (패키지.클래스명) => (클래스명)
mybatis.type-aliases-package=com.firstshop.mall
